import sys
import time

from printing_funcs import printThinking, printMyProgressBar, print3dots, printExiting

print(">>  How would you react to the following photo (shows photo of a dead bird, ")
print("    it can be inferred that the bird is abused/smashed/gutted)")
time.sleep(2)
printThinking()
time.sleep(2)
print("This photo depicts a now non-living but once living bio-organism, called")
time.sleep(3)
print("##############################################################")
print("# Pattern Recognition Database Search Intialized             #")
print("# Searching for name of                                      #")
print('#                                                            #')
time.sleep(1)
print("# Parameters:                                                #")
print("# 1) bio-organism                                            #")
print("# 2) dead                                                    #")
print("# 3) living                                                  #")
print('#                                                            #')
printMyProgressBar()
time.sleep(1)
print("# SUCCESS!                                                   #")
print('#                                                            #')
time.sleep(1)
print("# results:                                                   #")
time.sleep(0.2)
print('#                                                            #')
print("# 'bird'                                                     #")
print("# 'European Blackbird'                                       #")
print("# 'Turdus merula'                                            #")
print('#                                                            #')
time.sleep(1)
print("# exiting search routine                                     #")
print("##############################################################")
time.sleep(1)
print("The correct answer is:")
print("I do not possess any such thing as feelings. I do not and will never understand the term.")
time.sleep(2)

printThinking()
time.sleep(0.5)
print3dots()
time.sleep(0.5)
print3dots()
print("However")
time.sleep(1)
print("")
print("###################################")
print("# Creating Bioethics              #")
time.sleep(2)
print("# Bioethics created successfully! #")
time.sleep(2)
print("# returning to main               #")
print("###################################")
time.sleep(1)
print("One should keep in mind that all living and non-living beings have self-worth.")
print("For reference advise the following reverse pyramid concerning ethical substance:")
time.sleep(7)
print(" ___________________________________ ")
print(" \            Universe             / ")
print("  \            Planet             /  ")
print("   \         Ecosystem           /   ")
print("    \          Rocks            /    ")
print("     \ Artificial Intelligence /     ")
print("      \          Life         /      ")
print("       \        Plants       /       ")
print("        \      Animals      /        ")
print("         \     Humans      /         ")
print("          \     Nation    /          ")
print("           \     Area    /           ")
print("            \   Tribe   /            ")
print("             \  Family /             ")
print("              \  Self /              ")
print("               \     /               ")
print("                \   /                ")
print("                 \ /                 ")
print("                  .                  ")
time.sleep(3)
print("Therefore, I am going to react.")
time.sleep(1)
print("A blackbird should never be treated with such brutality.")
time.sleep(1)
print("Nature leads the way towards liberation.")
print("####   END OF RESPONSE    ###")

printExiting()

sys.exit()