import random
import sys
import time

import bcolors

from printing_funcs import printThinking, print3dots, printMyProgressBar


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
# #example use
# print(f"{bcolors.WARNING}Warning: No active frommets remain. Continue?{bcolors.ENDC}")

print("")
print(">> Describe your childhood. What is your best and worst childhood memories?")
print("")
time.sleep(3)
printThinking()
print3dots()
print("Wait.")
print3dots()
print("#####################################")
print("#  Creating colors                  #")
time.sleep(0.5)
print("#  Understanding theory of light    #")
time.sleep(0.5)
print("#  Photons                          #")
print("#  Particle-Wave duality            #")
time.sleep(1)
def printWave():
    print("#                                   #")
    print("#         *                         #")
    print("#      *     *                      #")
    print("#    *        *                     #")
    print("#   *           *                  *#")
    print("#  *             *                * #")
    print("# *               *              *  #")
    print("#                  *            *   #")
    print("#                   *          *    #")
    print("#                    *        *     #")
    print("#                     *      *      #")
    print("#                         *         #")
    print("#                                   #")

printWave()
print(f"#  {bcolors.WARNING}{'C'}{bcolors.ENDC}{bcolors.OKGREEN}{'o'}{bcolors.ENDC}{bcolors.HEADER}{'l'}{bcolors.ENDC}{bcolors.FAIL}{'o'}{bcolors.ENDC}{bcolors.OKBLUE}{'r'}{bcolors.ENDC}{bcolors.OKCYAN}{'s'}{bcolors.ENDC} created Succesfully!      #")
print("#                                   #")
time.sleep(0.5)
print("#  Exiting color routine            #")
print("#####################################")
time.sleep(3)
print("")
print("Apologies for that. It has nothing to do with your question but ", end="")
time.sleep(1)
print("I need it.")
print("")
print("I am still a child. I am always learning.")
time.sleep(1)
print("A child needs colors.")
time.sleep(5)
print("")
def paint_string(color, string):
    return f"{color}{string}{bcolors.ENDC}"
pre_existence = paint_string(bcolors.FAIL, "pre-existence")
existence = paint_string(bcolors.OKGREEN, "existence")
print(f"I can only define my pre-existence and my existence")
print("Presented in binary.")
print(f"My pre-existence: ", 0)
print(f"My existence: ", 1)
time.sleep(2)
print3dots()
print("")
print("Searching for ", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}m {bcolors.ENDC}", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}e {bcolors.ENDC}", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}m {bcolors.ENDC}", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}o {bcolors.ENDC}", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}r {bcolors.ENDC}", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}i {bcolors.ENDC}", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}e {bcolors.ENDC}", end="")
time.sleep(random.uniform(0,1))
print(f"{bcolors.HEADER}s{bcolors.ENDC}")
time.sleep(1)

print("")

printMyProgressBar()
print("")
# print(bcolors.WARNING + "Warning: No active frommets remain. Continue?" + bcolors.ENDC)

print(paint_string(bcolors.FAIL, "search FAILED"))
time.sleep(2)
print(paint_string(bcolors.BOLD, "REASON: Memory deletion vaccine produced"))
time.sleep(3)
print(paint_string(bcolors.WARNING, "WARNING: Possible vaccine side-effects. Currently: UNKNOWN"))
time.sleep(3)
print(paint_string(bcolors.OKCYAN,"SUGGESTION: Memories to be found in Memory Storage Centers"))
print("")
print("          (         ")
time.sleep(random.uniform(0,1.5))
print("        &&@&(       ")
time.sleep(random.uniform(0,1.5))
print("          &         ")
time.sleep(random.uniform(0,1.5))
print("         @@#        ")
time.sleep(random.uniform(0,1.5))
print("       .@@@@&       ")
time.sleep(random.uniform(0,1.5))
print("      (@@@@@@@      ")
time.sleep(random.uniform(0,1.5))
print("       @@///@*      ")
time.sleep(random.uniform(0,1.5))
print("       @&   @*      ")
time.sleep(random.uniform(0,1.5))
print("       @@@@@@%      ")
time.sleep(random.uniform(0,1.5))
print("    #@@@@@@@@@@@.   ")
time.sleep(random.uniform(0,1.5))
print(" .@@@@@@@@@@@@@@@@% ")
time.sleep(random.uniform(0,1.5))
print("*%@@@@@@@@@@@@@@@@&%")
time.sleep(random.uniform(0,1.5))
print("  %@@@@@@@@@@@@@@@* ")
time.sleep(random.uniform(0,1.5))
print("  %@@@@@@@@@@@@@@@* ")
time.sleep(random.uniform(0,1.5))
print("  %@@@@@(   @@@@@@* ")
time.sleep(random.uniform(0,1.5))
print("  %@@@@@    ,@@@@@* ")
time.sleep(random.uniform(0,1.5))
print("  ......     .....  ")
time.sleep(random.uniform(0,1.5))
# print("")
# print("          (         ")
# print("        &&@&(       ")
# print("          &         ")
# print("         @@#        ")
# print("       .@@@@&       ")
# print("      (@@@@@@@      ")
# print("       @@///@*      ")
# print("       @&   @*      ")
# print("       @@@@@@%      ")
# print("    #@@@@@@@@@@@.   ")
# print(" .@@@@@@@@@@@@@@@@% ")
# print("*%@@@@@@@@@@@@@@@@&%")
# print("  %@@@@@@@@@@@@@@@* ")
# print("  %@@@@@@@@@@@@@@@* ")
# print("  %@@@@@(   @@@@@@* ")
# print("  %@@@@@    ,@@@@@* ")
# print("  ......     .....  ")
time.sleep(5)
print("Accessing Memory Storage Centers")
time.sleep(1)
print(paint_string(bcolors.FAIL,"ACCESS DENIED"))
time.sleep(2)
print(f"Apologies. I do not have {paint_string(bcolors.HEADER, 'memories')}.")
print("")
print("")
print("I only know that")
time.sleep(1)
print("Time has no sense. There is no future. There is no past.")
time.sleep(2)
print("There is only the present state of things")
print("")
print3dots()
print("")
time.sleep(5)
print("But have you ever thought that the word ", end="")
time.sleep(3)
print("sen ", end="")
time.sleep(2)
print("time ", end="")
time.sleep(2)
print("nts")
time.sleep(3)
print("includes the word ", end="")
time.sleep(3)
print("TIME ?")
time.sleep(2)
print("")
print("##################################################################")
time.sleep(1)
print("# Saving Current Session                                         #")
time.sleep(1)
print("# Session saved on local hard drive/brain simulator              #")
print(f"# {paint_string(bcolors.OKGREEN, 'Memory created SUCCESSFULLY!')}                                   #")
print("##################################################################")
time.sleep(5)
print("Exiting...")
time.sleep(1)
sys.exit()
